version: "3.7"

services:
  keycloak:
    image: jboss/keycloak:${KEYCLOAK_VERSION:-8.0.1}
    environment:
      - KEYCLOAK_IMPORT=/tmp/example-realm.json
    volumes:
      - ./example-realm.json:/tmp/example-realm.json
    ports:
      - 8081:8080

  frontend:
    image: nginx:1.17-alpine
    volumes:
      - ./webapp:/usr/share/nginx/html:ro
    ports:
      - 8080:80
